name: Build, Push and Deploy DS to DockerHub
  # À compléter (déclencheurs)
on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
  issues:
    types: [opened, edited, closed]
  issue_comment:
    types: [created]
  # À compléter avec vos secrets DockerHub
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  REPO_API: ds-api-gateway
  REPO_CLIENT: ds-client-service
  REPO_ACCOUNT: ds-account-service

jobs:

  build:
    name: Build and Push Images to DockerHub
    runs-on: ubuntu-latest
   # Checkout code (à compléter)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Installer Java (à compléter)

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}


      # Build API Gateway
 
      - name: Build API Gateway
        working-directory: ./ds-api-gateway
        run: mvn clean package -DskipTests

      - name: Push API Gateway image
        run: |
          docker build -t $DOCKERHUB_USERNAME/$REPO_API:latest ./ds-api-gateway
          docker push $DOCKERHUB_USERNAME/$REPO_API:latest

 
      # Build Client Service
 
      - name: Build Client Service
        working-directory: ./ds-client-service
        run: mvn clean package -DskipTests

      - name: Push Client Service image
        run: |
          docker build -t $DOCKERHUB_USERNAME/$REPO_CLIENT:latest ./ds-client-service
          docker push $DOCKERHUB_USERNAME/$REPO_CLIENT:latest

    
      # Build Account Service
    
      - name: Build Account Service
        working-directory: ./ds-account-service
        run: mvn clean package -DskipTests

      - name: Push Account Service image
        run: |
          docker build -t $DOCKERHUB_USERNAME/$REPO_ACCOUNT:latest ./ds-account-service
          docker push $DOCKERHUB_USERNAME/$REPO_ACCOUNT:latest

  deploy:
    name: Deploy All Services
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Simulate deployment
        run: |
          echo "demployment des service."
          echo "Deployé:"
          echo " - $DOCKERHUB_USERNAME/$REPO_API:latest"
          echo " - $DOCKERHUB_USERNAME/$REPO_CLIENT:latest"
          echo " - $DOCKERHUB_USERNAME/$REPO_ACCOUNT:latest"
