name: Build, Push and Deploy DS to DockerHub

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  REPO_API: ds-api-gateway
  REPO_CLIENT: ds-client-service
  REPO_ACCOUNT: ds-account-service

jobs:

  build:
    name: Build and Push Images to DockerHub
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Installer Java
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # Se connecter à DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build API Gateway
      - name: Build & Push API Gateway
        working-directory: ds-api-gateway
        run: |
          docker build -t $DOCKERHUB_USERNAME/${{ env.REPO_API }} .
          docker push $DOCKERHUB_USERNAME/${{ env.REPO_API }}

      # Build Client Service
      - name: Build & Push Client Service
        working-directory: ds-client-service
        run: |
          docker build -t $DOCKERHUB_USERNAME/${{ env.REPO_CLIENT }} .
          docker push $DOCKERHUB_USERNAME/${{ env.REPO_CLIENT }}

      # Build Account Service
      - name: Build & Push Account Service
        working-directory: ds-account-service
        run: |
          docker build -t $DOCKERHUB_USERNAME/${{ env.REPO_ACCOUNT }} .
          docker push $DOCKERHUB_USERNAME/${{ env.REPO_ACCOUNT }}

  deploy:
    name: Deploy All Services
    runs-on: ubuntu-latest
    needs: build   # dépendance
 
    steps:
      - name: Simulate deployment
        run: |
          echo "==============================================="
          echo "Simulating deployment of all services..."
          echo "API Gateway deployed."
          echo "Client Service deployed."
          echo "Account Service deployed."
          echo "All services deployed successfully!"
          echo "==============================================="
